### PR TITLE
Add space between navbar and headers when first element is not image

### PR DESCRIPTION
**Pull request by JonathanBuchh**

### CODE REVIEW

**Review by ErikBoesen — CHANGES_REQUESTED** [review]
I would prefer if we do this through CSS. You can do
```css
section h1:first-child {
    margin-top: 30px; /* or whatever */
}
```

**Comment by JonathanBuchh** [comment]
I increased the `margin-top` for `body > selection:first-of-type` to make sure that there wasn't extra spacing for h1 elements that were under a jumbotron, since they already had adequate spacing.

**Review by AndrewLester — APPROVED** [review]

**Comment by AndrewLester** [comment]
@JonathanBuchh You should be able to merge your own pull requests now. You can wait for Erik to review this one, but in the future you can merge your own (requesting a review anyways is helpful though).

**Comment by JonathanBuchh** [comment]
@AndrewLester thanks. I plan to continue to make pull requests to ensure I abide by standards.

**Review by ErikBoesen — APPROVED** [review]

**Pull request merged**
